### ISSUE TITLE
Custom Muscle Groups not Displaying Correctly on Exercises

### ISSUE THREAD

**Issue by TimKamppinen** [astashov/liftosaur#365]
After creating some custom muscle groups and hiding some of the default groups, when I view an exercise, the custom muscle groups are showing up as a random-letter identifier instead of the actual name that I gave to the group.

<img width="862" height="294" alt="Image" src="https://github.com/user-attachments/assets/c5696d93-5163-4998-8b7b-1b13445feca1" />

Also, there appears to be no way to edit the name of a custom muscle group once it's created.

**Comment by astashov** [comment]
Fixed by e07b91ddb20a4b7a3f99cd57897c0af712c0e1d0

**Comment by TimKamppinen** [comment]
> Fixed by [e07b91d](https://github.com/astashov/liftosaur/commit/e07b91ddb20a4b7a3f99cd57897c0af712c0e1d0)

It's not fixed on my end, here's a screenshot from today (app is up to date and has been refreshed many times):

![Image](https://github.com/user-attachments/assets/c1b78514-9df5-44ad-a316-25aabaa47a93)
